---
title: mascure`s blog
email: linzhouwzj@163.com
author: mascure
author_github: mascure
description: |
  What a lovely world!
baseurl: ""
url: http://mascure.info
paginate: 12
github:
  user: 
  repository: 
  url: 
  status: false
home_bgfile: bg.jpg
sass:
  sass_dir: assets/css
  style: compressed
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
gems:
- jekyll-paginate
exclude:
- vendor
